[phases.setup]
nixPkgs = ["nodejs", "python311", "postgresql", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
cmd = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.asgi:application --bind 0.0.0.0:$PORT" 