[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools", "python39Packages.wheel"]

[phases.install]
cmds = ["chmod +x railway-build.sh", "./railway-build.sh"]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT" 