[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash simplified.sh"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/"
interval = 5
timeout = 2
retries = 3
grace_period = 10

[deploy.envs]
PYTHONUNBUFFERED = "1"
PORT = "8080"
