[deploy]
startCommand = "./start_django.sh"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
interval = 30
timeout = 20
retries = 5
grace_period = 300

[deploy.envs]
PYTHONUNBUFFERED = "1"
DEBUG = "True"
PORT = "8080"
ALLOWED_HOSTS = "backend-production-49ec.up.railway.app,localhost,127.0.0.1"
DJANGO_SETTINGS_MODULE = "backend.settings"
STATIC_ROOT = "/app/staticfiles"
STATIC_URL = "/static/"
