[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn backend.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
restartPolicyMaxRetries = 10

[envs]
PORT.default = "8000"
PYTHON_VERSION.default = "3.10" 