[build]
builder = "DOCKERFILE"
watchPaths = ["requirements.txt", "Dockerfile", "build.sh"]
buildCommand = ""

[deploy]
healthcheckPath = "/railway-health/"
healthcheckTimeout = 300
numReplicas = 1
sleepApplication = false
restartPolicyMaxRetries = 5

[envs]
PORT.default = "8000"
PYTHON_VERSION.default = "3.10"
SKIP_PIP.default = "true" 