[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash startup.sh"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/"
interval = 30
timeout = 15
retries = 3
grace_period = 180

[deploy.envs]
PYTHONUNBUFFERED = "1"
DEBUG = "True" 