[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[deploy.healthcheck]
path = "/health/"
interval = 10
timeout = 5
retries = 3

[deploy.envs]
PYTHONUNBUFFERED = "1"

[env]
PORT = "8000" 