[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash startup.sh"
healthcheckPath = "/railway-health-app/railway/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/railway-health-app/railway/"
interval = 45
timeout = 30
retries = 5
grace_period = 300

[deploy.envs]
PYTHONUNBUFFERED = "1"
DEBUG = "True" 