[deploy]
startCommand = "python railway_health.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
interval = 30
timeout = 20
retries = 5
grace_period = 300

[deploy.envs]
PYTHONUNBUFFERED = "1"
DEBUG = "True"
PORT = "8080"
ALLOWED_HOSTS = "*"
DJANGO_SETTINGS_MODULE = "backend.settings"
