[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash startup.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 300

[deploy.healthcheck]
path = "/health/"
interval = 10
timeout = 5
retries = 3

[deploy.envs]
PYTHONUNBUFFERED = "1"

[env]
PORT = "8000" 