# Generated by Django 5.2.1 on 2025-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_add_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
