# Generated by Django 4.2.13 on 2025-06-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_position_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="level",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="path",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["level"], name="blog_commen_level_a5504a_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["path"], name="blog_commen_path_7e6893_idx"),
        ),
    ]
