# Generated by Django 4.2.13 on 2025-06-18 19:51

from django.db import migrations


def populate_comment_fields(apps, schema_editor):
    """
    Populate the level and path fields for existing comments.
    Since there is no parent_id field, we'll just set all comments as root level.
    """
    # Get the database connection
    db_alias = schema_editor.connection.alias
    
    # Set level=0 for all comments (no parent-child relationship)
    schema_editor.execute(
        "UPDATE blog_comment SET level = 0"
    )
    
    # Set path for comments using their ID (SQLite compatible)
    schema_editor.execute(
        "UPDATE blog_comment SET path = CAST(id AS TEXT)"
    )


def reverse_populate(apps, schema_editor):
    """
    Reverse operation - clear the level and path fields
    """
    schema_editor.execute(
        "UPDATE blog_comment SET level = 0, path = ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_add_comment_nesting_fields"),
    ]

    operations = [
        migrations.RunPython(populate_comment_fields, reverse_populate),
    ]
