# Generated by Django 4.2.13 on 2025-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_update_featured_field'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                -- Check if featured column exists
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'blog_blogpost'
                    AND column_name = 'featured'
                ) THEN
                    -- Add featured column if it doesn't exist
                    ALTER TABLE blog_blogpost ADD COLUMN featured boolean NOT NULL DEFAULT false;
                    CREATE INDEX blog_blogpost_featured_idx ON blog_blogpost (featured);
                ELSE
                    -- Set default value for existing rows where featured is NULL
                    UPDATE blog_blogpost SET featured = false WHERE featured IS NULL;
                    
                    -- Add NOT NULL constraint if it doesn't exist
                    ALTER TABLE blog_blogpost ALTER COLUMN featured SET NOT NULL;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
