# Generated by Django 4.2.13 on 2025-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief description of the post (max 300 characters). If left blank, will be auto-generated from content.', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes (auto-calculated based on content)'),
        ),
    ]
