# Generated by Django 4.2.23 on 2025-09-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_consolidated_comment_nesting"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Description for SEO (recommended: 150–160 characters)",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Title for SEO (recommended: 50–60 characters)",
                max_length=60,
                null=True,
            ),
        ),
    ]
