# Generated by Django 4.2.23 on 2025-09-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_blogpost_meta_description_blogpost_meta_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="schema_description",
            field=models.TextField(
                blank=True,
                help_text="Schema description (auto-generated from excerpt/content if empty)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="schema_headline",
            field=models.CharField(
                blank=True,
                help_text="Schema headline (max 110 characters, auto-generated from title if empty)",
                max_length=110,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="schema_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for schema image (auto-generated if empty)",
                max_length=125,
                null=True,
            ),
        ),
    ]
