# Generated by Django 4.2.23 on 2025-09-13 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_add_schema_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="schema_description",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="schema_headline",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="schema_image_alt",
        ),
    ]
